Auth pages frontend
ALCOpenSource/Mentor-Management-System-Team-2 pull request #66
Opened 2023-04-11 08:02 UTC by feisal-Codes

-Login page
-password reset page
-set new password page

uses css modules styling 

Note:  The Follwing downgrades were made from Nextjs and react.
"dependencies": {
    "next": "12.0.4",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },

The New set up by Akanbi is yet to be merged! 

Alternatively, this can be merged as the setup is the same as the one that is yet to be merged!

2023-04-11 10:26 UTC, dejetem commented
your pr is failing on codacy

2023-04-11 12:09 UTC, emmsdan requested changes
Nice work, but please, do a few more clean up.
also, remove unused images and codes

2023-04-11 12:09 UTC, emmsdan commented on frontend/mms-Admin/components/Icon.js
> +    console.log(icon)
remove console.log

2023-04-11 12:09 UTC, emmsdan commented on frontend/mms-Admin/Read.md
> -*[Contributor's wiki](https://github.com/ALCOpenSource/Mentor-Management-System-Team-2/wiki)
avoid making changes to read.me

2023-04-11 12:09 UTC, emmsdan commented on frontend/mms-Admin/components/PasswordReset.js
> +          fontWeight: "400",
no inline styling

2023-04-11 12:09 UTC, emmsdan commented on frontend/mms-Admin/components/PasswordReset.js
> +          fontWeight: "700",
No inline style

2023-04-11 12:09 UTC, emmsdan commented on frontend/mms-Admin/components/PasswordReset.js
> +      {showPassword && forgetPassword == false && (
instead of a loose false, please use `!forgetPassword` instead.

2023-04-11 12:09 UTC, emmsdan commented on frontend/mms-Admin/components/admin/Login.js
> +import styles from "../componentStyles/login.module.css";
This is better. stick to this

2023-04-11 22:30 UTC, feisal-Codes reviewed
made requested changes

2023-04-11 22:44 UTC, peculiaruc commented
@feisal-Codes I have fixed the Codacy issue here, Kindly resolve the conflict

2023-04-11 22:55 UTC, marksikaundi approved these changes

2023-04-11 22:55 UTC, marksikaundi commented on frontend/mms-Admin/styles/globals.css
Overall the inline styling was rejected by the team? For me i feel you would have done it perfect with tailwind CSS, because its easy and keeps your code base easy to read and maintainable. I would also recommend you use prettier for your code to be nicely formatted.....You  can install an extension if you, using visual studio code.

2023-04-11 22:59 UTC, feisal-Codes commented on frontend/mms-Admin/styles/globals.css
thank you for the suggestion. yes inline styling complicates the code. am using css modules for now.

2023-04-11 23:29 UTC, peculiaruc commented
> @peculiaruc we did a downgrade to next12 which is stable and react 17+ .. i would request you check the conflict on your end , if you can merge the new set up. (a previous set up by my fellow team was not yet approved.

I am not sure about the one you added in your new update. Kindly fix, please.

2023-04-12 02:13 UTC, feisal-Codes commented
@peculiaruc @emmsdan  please check this. The set up that the team is using. Thank you.  

https://github.com/Shegsdev/Mentor-Management-System-Team-2/tree/ch-frontend-setup/frontend/mms-Admin

2023-04-12 03:51 UTC, emmsdan approved these changes
LG (Looks good)

2023-04-12 03:52 UTC, merged