Ch/redesign dashboard layout
ALCOpenSource/Mentor-Management-System-Team-2 pull request #89
Opened 2023-04-16 14:17 UTC by Shegsdev

- redesign navbar
- redesign sidebar

2023-04-16 16:35 UTC, emmsdan requested changes
Your design is stretching and does not have a proper responsiveness

<img width="197" alt="Screenshot 2023-04-16 at 5 33 04 PM" src="https://user-images.githubusercontent.com/3631446/232327003-b0669ab4-c6fe-4c88-809c-5ff6b6533126.png">
<img width="422" alt="Screenshot 2023-04-16 at 5 33 25 PM" src="https://user-images.githubusercontent.com/3631446/232327014-87b0e517-109b-49e5-a606-c33dd506e1c1.png">

2023-04-17 04:24 UTC, feisal-Codes approved these changes

2023-04-17 14:22 UTC, emmsdan commented
@Shegsdev fix conflit

2023-04-17 14:56 UTC, Shegsdev commented
> @Shegsdev fix conflit

Done

2023-04-18 10:18 UTC, merged