Ft/dashboard admin app
ALCOpenSource/Mentor-Management-System-Team-2 pull request #98
Opened 2023-04-19 14:58 UTC by Shegsdev

2023-04-19 15:28 UTC, dejetem approved these changes
Good

2023-04-20 12:47 UTC, emmsdan requested changes
please, remove the inline style and package-lock.json

2023-04-20 12:47 UTC, emmsdan commented on frontend/mms-Admin/components/Layout/SideBar/SideBar.jsx
>        <Typography style={{ padding: "32px 55px" }}>
c

2023-04-20 12:47 UTC, emmsdan commented on frontend/mms-Admin/components/admin/dashboard/Reports.js
> +            <p style={{ margin: 0 }} className={styles.card_header_text}>Reports overview</p>
no inline style

2023-04-20 12:47 UTC, emmsdan commented on frontend/mms-Admin/components/admin/dashboard/Reports.js
> +                  <p style={{ margin: 0, fontSize: "20px" }}>{report.title}</p>
no inline style

2023-04-20 12:47 UTC, emmsdan commented on frontend/mms-Admin/components/admin/dashboard/Statistics.js
> +          borderRadius: "7px",
no inline style

2023-04-20 12:47 UTC, emmsdan commented on frontend/mms-Admin/components/admin/dashboard/Statistics.js
> +              style={{ color: "#fff", marginRight: "12px", marginBottom: 0 }}>
no inline style

2023-04-20 12:47 UTC, emmsdan commented on frontend/mms-Admin/components/admin/dashboard/Statistics.js
> +              justifyContent: "start",
no inline style

2023-04-20 12:47 UTC, emmsdan commented on frontend/mms-Admin/components/admin/dashboard/Statistics.js
> +                  width: "80%",
no inline style

2023-04-20 12:47 UTC, emmsdan commented on frontend/mms-Admin/components/admin/dashboard/Statistics.js
> +                <p style={{ margin: 0, fontSize: "20px" }}>{stat.title}</p>
no inline style

2023-04-20 12:47 UTC, emmsdan commented on frontend/mms-Admin/components/admin/dashboard/Tasks.js
> +          <p style={{ fontSize: "20px", color: "#f7feff", margin: 0 }}>In Progress</p>
no inline style

2023-04-20 12:47 UTC, emmsdan commented on frontend/mms-Admin/components/admin/dashboard/Tasks.js
> +                    <p style={{ margin: 0, fontSize: "20px" }}>{task.title}</p>
no inline style

2023-04-24 13:29 UTC, feisal-Codes approved these changes
Good work

2023-04-24 14:26 UTC, dejetem approved these changes

2023-04-24 14:41 UTC, emmsdan approved these changes

2023-04-24 14:41 UTC, merged