Mm task admin app sprint 2
ALCOpenSource/Mentor-Management-System-Team-2 pull request #99
Opened 2023-04-19 19:59 UTC by dejetem

https://user-images.githubusercontent.com/52535603/233185236-bff73a66-9ec2-4207-aebf-1f6e7182a2f6.mp4

2023-04-19 20:30 UTC, emmsdan requested changes
- Please, add functionality to the sidebar to enable users to select different tasks to display on the main task area
- when a user selects a task, it should show on the sidebar
- also please make this responsive

2023-04-19 20:33 UTC, dejetem commented
> * Please, add functionality to the sidebar to enable users to select different tasks to display on the main task area
> * when a user selects a task, it should show on the sidebar
> * also please make this responsive

Okay

2023-04-19 20:35 UTC, dejetem commented
> * Please, add functionality to the sidebar to enable users to select different tasks to display on the main task area
> * when a user selects a task, it should show on the sidebar
> * also please make this responsive

but their is no mobile design on the figma

2023-04-24 21:22 UTC, shegs-devv commented on frontend/mms-Admin/public/assets/images/Mentor.svg
These icons have been added already

2023-04-24 21:32 UTC, dejetem commented on frontend/mms-Admin/public/assets/images/Mentor.svg
Okay

2023-04-24 21:37 UTC, Shegsdev approved these changes
Very well

2023-04-24 21:39 UTC, feisal-Codes approved these changes

2023-04-24 22:02 UTC, emmsdan approved these changes

2023-04-24 22:02 UTC, merged